name: "Don't Make Me Laugh"
favicon: null
layout_spectrum: 0.12758
typography_spectrum: 0.9431360063608736
title: "Don't Make Me Laugh - Dontlol.com"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2caa23'
    - '#ffcd18'
    - '#f5ef91'
    - '#84dce8'
    - '#393d47'
  brandStrength: 0.4375
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 1
purpose: []
