name: "Don't Make Me Laugh"
favicon: null
layout_spectrum: 0.12758
typography_spectrum: 0.9431360063608736
title: "Don't Make Me Laugh - Dontlol.com"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.1875
  lightness: 0.875
  saturation: 0.14844991965219378
  rhythmicContrast: 0.75
purpose: []
