name: makemelaugh
favicon: null
layout_spectrum: 0.6268271489534527
typography_spectrum: 0.9431360063608736
title: Make Me Laugh
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.9982726296875626
  lightness: 0.4770469288341701
  saturation: 0.14844991965219378
  rhythmicContrast: 0.531459957594052
purpose: []
