name: "Don't Make Me Laugh"
favicon: null
layout_spectrum: 0.12758
typography_spectrum: 0.9431360063608736
title: "Don't Make Me Laugh - Dontlol.com"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fe0000'
    - '#ff7f00'
    - '#ffff01'
    - '#fe4600'
    - '#fece00'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
