name: "Don't Make Me Laugh"
favicon: null
layout_spectrum: 0.12758
typography_spectrum: 0.9431360063608736
title: "Don't Make Me Laugh - Dontlol.com"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c8ebb1'
    - '#689864'
    - '#405d00'
    - '#336799'
  brandStrength: 0.4375
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
